name: 'Post Image'
description: 'Posts a image on the comment section in a pull request'
branding:
    icon: 'image'
    color: 'black'
inputs:
    path:
        description: 'Image path glob (Ex: **/*.png)'
        required: true
        default: ''
    title:
        description: 'Comment title'
        required: false
        default: ''
    uploadHost:
        description: 'Upload host (by default: https://0x0.st/)'
        required: false
        default: 'https://0x0.st/'
    annotationTag:
        description: 'The tag to look for in the provided images base64 name (ex: tests/mytest.spec.js[--]80:40.png)'
        required: false
        default: '[--]'
    annotationLevel:
        description: 'The annotation level (Supported values: notice, warning, failure)'
        required: false
        default: 'notice'
runs:
    using: 'node16'
    main: './index.mjs'
